### ISSUE TITLE
suggestions - colors and dull

### ISSUE THREAD

**Issue by surytrap** [prophetofxenu/UKFreshnessCoach#1]
option to customize flashing colors (defaults would be white and orange for used, red and orange for stale, red and black for dull)

talking about dull, add it in as another message

**Comment by prophetofxenu** [comment]
Good suggestions, thanks for the feedback. Shouldn't be hard to add, but may be the end of the week before I can work on this again.

**Comment by prophetofxenu** [comment]
@surytrap These changes are now available on Thunderstore, thanks again for the feedback :)
