### ISSUE TITLE
Incorrect Descriptions for UsedPrimaryColor and UsedSecondaryColor

### ISSUE THREAD

**Issue by UntotenTheo** [prophetofxenu/UKFreshnessCoach#3]
exactly what it says on the tin
![image](https://github.com/prophetofxenu/UKFreshnessCoach/assets/75056493/d5f6f4df-de2a-4ac0-9446-a8e2a0952f87)

**Comment by prophetofxenu** [comment]
embarrassing, one sec

**Comment by prophetofxenu** [comment]
@UntotenTheo Should be fixed, thanks.
