### ISSUE TITLE
Option to disable text shaking

### ISSUE THREAD

**Issue by UntotenTheo** [prophetofxenu/UKFreshnessCoach#4]
Yeah thats all

good mod btw, i likey

**Comment by prophetofxenu** [comment]
Good idea, and I'll add one to disable the flashing while I'm at it. Thanks,

Glad you like.

**Comment by UntotenTheo** [comment]
👍 take your time boss

**Comment by prophetofxenu** [comment]
@UntotenTheo Should be available in Thunderstore now.

**Comment by UntotenTheo** [comment]
you rock, thanks dawg :)
